import { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { AlertTriangle, BarChart3, CalendarDays, ChevronLeft, ChevronRight, Clock3, Gauge, History, Plane, Play, Plus, Wrench, X } from 'lucide-react'
import { fleetResourceSnapshot, localDateIso, overlapsSlot, slotStart, type MissionStatus, type ScheduledMission } from './scheduleData'
import { MissionExportActions } from './MissionExportActions'

type CatalogUav = { id:string; name:string; status:string; maintenance_due_hours:number; type?:string; maintenance_metric?:'flights'|'engine_hours'|'flight_hours'|'unverified'; maintenance_interval?:number|null }
export type PlannerCalendarMode = 'flights'|'maintenance'|'combined'
export type MaintenanceDraft = { uavId:string; date:string; time:string; duration:number; title:string; location:string }

const statusLabel:Record<MissionStatus,string>={completed:'Выполнено',active:'В работе',planned:'Запланировано',maintenance:'ТО'}
const monthNames=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь']
const weekDays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс']
const monthKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`
const humanDate=(date:string)=>new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date}T12:00:00`))

function DayPlan({date,missions,uavs,onClose,onMission,onReplay}:{date:string;missions:ScheduledMission[];uavs:CatalogUav[];onClose:()=>void;onMission:(mission:ScheduledMission)=>void;onReplay:(mission:ScheduledMission)=>void}){
  const dayMissions=missions.filter(m=>m.date===date).sort((a,b)=>a.time.localeCompare(b.time))
  const busyIds=new Set(dayMissions.map(m=>m.uavId)),hours=dayMissions.reduce((sum,m)=>sum+m.duration,0),conflictIds=new Set<string>()
  dayMissions.forEach((mission,index)=>dayMissions.slice(index+1).forEach(other=>{if(mission.uavId===other.uavId&&overlapsSlot(mission,other.date,other.time,other.duration))conflictIds.add(mission.uavId)}))
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==='Escape'&&onClose();window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose])
  return createPortal(<div className="day-plan-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="day-plan-modal" role="dialog" aria-modal="true">
    <header><div><span>СУТОЧНЫЙ ПЛАН</span><h2>{humanDate(date)}</h2><p>Вылеты и техническое обслуживание на единой временной шкале.</p></div><button onClick={onClose} aria-label="Закрыть"><X/></button></header>
    <div className="day-plan-kpis"><article><Plane/><span><small>Задействовано</small><b>{busyIds.size} / {uavs.length}</b></span></article><article><Clock3/><span><small>Плановая занятость</small><b>{hours.toFixed(1)} ч</b></span></article><article><BarChart3/><span><small>Загрузка флота</small><b>{uavs.length?Math.round(busyIds.size/uavs.length*100):0}%</b></span></article><article className={conflictIds.size?'warning':''}><AlertTriangle/><span><small>Конфликты</small><b>{conflictIds.size}</b></span></article></div>
    <div className="day-timeline"><div className="timeline-axis"><span>Борт</span>{[6,9,12,15,18,21].map(hour=><b key={hour} title={`Время по местному часовому поясу: ${String(hour).padStart(2,'0')}:00`}>{String(hour).padStart(2,'0')}:00</b>)}</div>{uavs.map(uav=>{const assigned=dayMissions.filter(m=>m.uavId===uav.id);return <div className={`timeline-row ${conflictIds.has(uav.id)?'has-conflict':''}`} key={uav.id}><div className="timeline-uav"><strong>{uav.name}</strong><small>{assigned.some(m=>m.status==='maintenance')?'ТО':assigned.some(m=>m.status==='active')?'В полёте':assigned.length?'Зарезервирован':'Свободен'}</small></div><div className="timeline-track">{assigned.map(mission=>{const [hour,minute]=mission.time.split(':').map(Number),left=Math.max(0,((hour+minute/60-6)/15)*100),width=Math.min(100-left,mission.duration/15*100);return <div key={mission.id} className={`timeline-mission ${mission.status}`} style={{left:`${left}%`,width:`${Math.max(width,4)}%`}}><button className="timeline-mission-main" onClick={()=>onMission(mission)} title={`Открыть карточку: ${mission.title}`}><b>{mission.time}</b><span>{mission.title}</span></button>{mission.simulation&&<button className="timeline-mission-play" onClick={()=>onReplay(mission)} title={mission.status==='active'?'Открыть текущий полёт':mission.status==='planned'?'Запустить симуляцию':'Смотреть повтор'} aria-label={mission.status==='active'?'Открыть текущий полёт':'Запустить демо'}><Play size={12}/></button>}</div>})}</div></div>})}</div>
    <footer><div><i className="planned"/> План <i className="active"/> В работе <i className="completed"/> Выполнено <i className="maintenance"/> ТО</div><span>{dayMissions.length?`${dayMissions.length} событий · ${uavs.length-busyIds.size} бортов свободно`:'Весь флот свободен'}</span></footer>
  </section></div>,document.body)
}

function MaintenanceModal({uavs,missions,initialUavId,onClose,onCreate}:{uavs:CatalogUav[];missions:ScheduledMission[];initialUavId:string|null;onClose:()=>void;onCreate:(draft:MaintenanceDraft)=>Promise<unknown>}){
  const [draft,setDraft]=useState<MaintenanceDraft>(()=>{
    const uavId=initialUavId||uavs[0]?.id||'',tomorrow=new Date()
    tomorrow.setDate(tomorrow.getDate()+1)
    for(let day=0;day<31;day++){
      const date=localDateIso(tomorrow)
      if(!missions.some(m=>m.uavId===uavId&&m.status!=='completed'&&overlapsSlot(m,date,'09:00',2)))return{uavId,date,time:'09:00',duration:2,title:'Плановое техническое обслуживание',location:'Сервисная зона'}
      tomorrow.setDate(tomorrow.getDate()+1)
    }
    return{uavId,date:localDateIso(tomorrow),time:'09:00',duration:2,title:'Плановое техническое обслуживание',location:'Сервисная зона'}
  })
  const [saving,setSaving]=useState(false),[error,setError]=useState('')
  const conflict=missions.find(m=>m.uavId===draft.uavId&&m.status!=='completed'&&overlapsSlot(m,draft.date,draft.time,draft.duration))
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==='Escape'&&onClose();window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose])
  return createPortal(<div className="maintenance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><form className="maintenance-modal" onSubmit={async event=>{event.preventDefault();if(conflict)return;setSaving(true);setError('');try{await onCreate(draft);onClose()}catch(value){setError(value instanceof Error?value.message:'Не удалось запланировать ТО')}finally{setSaving(false)}}}>
    <header><div><span>ЭКСПЛУАТАЦИЯ ФЛОТА</span><h2>Запланировать обслуживание</h2><p>Интервал будет заблокирован для назначения полётных заданий.</p></div><button type="button" onClick={onClose}><X/></button></header>
    <div className="maintenance-form-grid"><label>Борт<select value={draft.uavId} onChange={e=>setDraft({...draft,uavId:e.target.value})}>{uavs.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Вид работ<select value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}><option>Плановое техническое обслуживание</option><option>Диагностика силовой установки</option><option>Обслуживание энергосистемы</option><option>Регламент планера</option></select></label><label>Дата<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Начало<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Длительность, ч<input type="number" min="0.5" step="0.5" value={draft.duration} onChange={e=>setDraft({...draft,duration:Number(e.target.value)})}/></label><label>Место<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label></div>
    {conflict&&<div className="maintenance-conflict"><AlertTriangle/> Интервал занят: {conflict.time} · {conflict.title}</div>}{error&&<div className="maintenance-conflict">{error}</div>}
    <footer><button type="button" onClick={onClose}>Отмена</button><button className="primary" disabled={saving||!!conflict||!draft.uavId}>{saving?'Сохраняем…':'Запланировать ТО'}</button></footer>
  </form></div>,document.body)
}

export function CalendarDashboard({uavs,missions,onReplay,onCreateMaintenance,initialMode='flights',focusUavId=null,maintenanceDraftUavId=null,onMaintenanceDraftConsumed}:{uavs:CatalogUav[];missions:ScheduledMission[];onReplay:(mission:ScheduledMission)=>void;onCreateMaintenance:(draft:MaintenanceDraft)=>Promise<unknown>;initialMode?:PlannerCalendarMode;focusUavId?:string|null;maintenanceDraftUavId?:string|null;onMaintenanceDraftConsumed?:()=>void}){
  const [monthOffset,setMonthOffset]=useState(0),[mode,setMode]=useState<PlannerCalendarMode>(initialMode),[status,setStatus]=useState<'all'|MissionStatus>('all'),[uavId,setUavId]=useState(focusUavId||'all'),[selectedId,setSelectedId]=useState(missions.find(m=>m.status==='active')?.id||missions[0]?.id||''),[selectedDay,setSelectedDay]=useState<string|null>(null),[maintenanceOpen,setMaintenanceOpen]=useState(false)
  useEffect(()=>setMode(initialMode),[initialMode]);useEffect(()=>{if(focusUavId)setUavId(focusUavId)},[focusUavId]);useEffect(()=>{if(maintenanceDraftUavId){setMode('maintenance');setUavId(maintenanceDraftUavId);setMaintenanceOpen(true);onMaintenanceDraftConsumed?.()}},[maintenanceDraftUavId])
  const now=new Date(),month=new Date(now.getFullYear(),now.getMonth()+monthOffset,1),key=monthKey(month),today=localDateIso(now)
  const modeMissions=useMemo(()=>missions.filter(m=>mode==='combined'||(mode==='maintenance'?m.status==='maintenance':m.status!=='maintenance')),[missions,mode])
  const filtered=useMemo(()=>modeMissions.filter(m=>m.date.startsWith(key)&&(status==='all'||m.status===status)&&(uavId==='all'||m.uavId===uavId)),[modeMissions,key,status,uavId])
  const selected=modeMissions.find(m=>m.id===selectedId)||filtered[0],firstDay=(month.getDay()+6)%7,dayCount=new Date(month.getFullYear(),month.getMonth()+1,0).getDate()
  const flightMissions=filtered.filter(m=>m.status!=='maintenance'),maintenanceMissions=filtered.filter(m=>m.status==='maintenance'),hoursCompleted=flightMissions.filter(m=>m.status==='completed'||m.status==='active').reduce((sum,m)=>sum+m.duration,0),hoursPlanned=flightMissions.filter(m=>m.status==='planned').reduce((sum,m)=>sum+m.duration,0),ready=uavs.filter(u=>u.status==='ready').length,nearService=uavs.filter(u=>u.maintenance_metric!=='flights'&&fleetResourceSnapshot(u,missions,now).risk!=='normal').length
  const title=mode==='flights'?'Календарь заданий':mode==='maintenance'?'Календарь технического обслуживания':'Общий эксплуатационный план'
  return <section className={`calendar-workspace calendar-mode-${mode}`} aria-label="Планировщик флота">
    <header className="calendar-title"><div><span>ЭКСПЛУАТАЦИЯ ФЛОТА</span><h1>{title}</h1><p>Полёты, загрузка и технический ресурс флота в едином рабочем представлении.</p></div><nav className="planner-mode-switch" aria-label="Режим планировщика"><button className={mode==='flights'?'active':''} onClick={()=>{setMode('flights');setStatus('all')}}><Plane/>Полётные задания</button><button className={mode==='maintenance'?'active':''} onClick={()=>{setMode('maintenance');setStatus('all')}}><Wrench/>Техническое обслуживание</button><button className={mode==='combined'?'active':''} onClick={()=>{setMode('combined');setStatus('all')}}><CalendarDays/>Общий план</button></nav></header>
    <div className="calendar-kpis"><article><Clock3/><small>{mode==='maintenance'?'Занято под ТО':'Налёт за период'}</small><strong>{(mode==='maintenance'?maintenanceMissions.reduce((s,m)=>s+m.duration,0):hoursCompleted).toFixed(1)} ч</strong><span>{mode==='maintenance'?'плановые работы':'выполненные и активные'}</span></article><article><CalendarDays/><small>{mode==='maintenance'?'Запланировано ТО':'Запланировано'}</small><strong>{mode==='maintenance'?maintenanceMissions.length:`${hoursPlanned.toFixed(1)} ч`}</strong><span>{mode==='maintenance'?'сервисных окон':`${flightMissions.filter(m=>m.status==='planned').length} заданий`}</span></article><article><Plane/><small>Готовность флота</small><strong>{ready} / {uavs.length}</strong><span>бортов готовы</span></article><article className={nearService?'attention':''}><Wrench/><small>Прогноз ресурса</small><strong>{nearService}</strong><span>требуют внимания</span></article></div>
    <div className="planner-dashboard-grid"><div className="planner-calendar-column"><div className="calendar-filters"><label>Статус<select value={status} onChange={e=>setStatus(e.target.value as 'all'|MissionStatus)}><option value="all">Все статусы</option>{mode!=='maintenance'&&<><option value="planned">Запланировано</option><option value="active">В работе</option><option value="completed">Выполнено</option></>} {(mode==='maintenance'||mode==='combined')&&<option value="maintenance">ТО</option>}</select></label><label>Борт<select value={uavId} onChange={e=>setUavId(e.target.value)}><option value="all">Весь флот</option>{uavs.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label>{(mode==='maintenance'||mode==='combined')&&<button className="schedule-maintenance-button" onClick={()=>setMaintenanceOpen(true)}><Plus/>Запланировать ТО</button>}<span>Нажмите на день, чтобы открыть суточный план</span><div className="calendar-period"><button onClick={()=>setMonthOffset(v=>v-1)}><ChevronLeft/></button><strong>{monthNames[month.getMonth()]} {month.getFullYear()}</strong><button onClick={()=>setMonthOffset(v=>v+1)}><ChevronRight/></button><button className="today-button" onClick={()=>setMonthOffset(0)}>Сегодня</button></div></div>
      <section className="month-card"><div className="week-header">{weekDays.map(day=><span key={day}>{day}</span>)}</div><div className="month-grid">{Array.from({length:firstDay}).map((_,i)=><div className="calendar-day outside" key={`blank-${i}`}/>)}{Array.from({length:dayCount}).map((_,i)=>{const day=i+1,date=`${key}-${String(day).padStart(2,'0')}`,dayMissions=filtered.filter(m=>m.date===date);return <div className={`calendar-day ${date===today?'today':''} ${dayMissions.length?'has-events':''}`} key={date} role="button" tabIndex={0} onClick={()=>setSelectedDay(date)}><b>{day}</b>{dayMissions.slice(0,3).map(m=><button className={`mission-chip ${m.status}`} key={m.id} title={`${m.time} · ${m.title} · ${statusLabel[m.status]}`} onClick={e=>{e.stopPropagation();setSelectedId(m.id);setSelectedDay(date)}}><span>{m.time}</span>{m.title}</button>)}{dayMissions.length>3&&<button className="calendar-more" onClick={e=>{e.stopPropagation();setSelectedDay(date)}} title={`Открыть все ${dayMissions.length} событий`}>+{dayMissions.length-3} ещё</button>}</div>})}</div>{!filtered.length&&<div className="calendar-empty">В этом месяце нет событий с выбранными фильтрами.</div>}</section></div>
      <aside className="planner-sidebar"><section className="fleet-health"><header><div><h2>Ресурс и прогноз износа</h2><p>Индексы узлов демонстрационные. Регламент ТО зависит от серии и журнала полётов.</p></div><Gauge/></header><div className="fleet-resource-list">{uavs.map(uav=>({uav,snapshot:fleetResourceSnapshot(uav,missions,now)})).sort((a,b)=>a.snapshot.projectedRemainingHours-b.snapshot.projectedRemainingHours).map(({uav,snapshot})=><article className="fleet-resource-row" key={uav.id}><header><strong>{uav.name}</strong><span>план {snapshot.plannedHours.toFixed(1)} ч</span><b className={uav.maintenance_metric!=='flights'&&snapshot.risk!=='normal'?'warning':''}>{uav.maintenance_metric==='flights'?`ТО / ${uav.maintenance_interval} полётов · нужен журнал`:uav.maintenance_metric==='engine_hours'?`до ТО ${snapshot.projectedRemainingHours.toFixed(1)} моточасов`:`учебный остаток ${snapshot.projectedRemainingHours.toFixed(1)} ч`}</b></header><div>{([['П',snapshot.airframe,'Планер'],['С',snapshot.propulsion,'Силовая установка'],['Э',snapshot.power,'Энергосистема']] as const).map(([name,value,label])=><span className={`resource-meter ${value>=65?'critical':value>=40?'attention':'normal'}`} key={name} title={`${label}: ${value}% · демонстрационная оценка`}><small>{name}</small><i><b style={{width:`${value}%`}}/></i><em>{value}%</em></span>)}</div></article>)}</div></section>
      <section className="mission-detail"><header><span className={`status-dot ${selected?.status||'planned'}`}/><small>{selected?statusLabel[selected.status]:'Выберите событие'}</small></header>{selected?<><h2>{selected.title}</h2><p>{selected.date.split('-').reverse().join('.')} · {selected.time} · {selected.location}</p><dl><dt>БВС</dt><dd>{selected.uavName}</dd><dt>{selected.status==='maintenance'?'Работы':'Результат'}</dt><dd>{selected.product}</dd><dt>Длительность</dt><dd>{selected.duration.toFixed(1)} ч</dd></dl>{selected.status==='maintenance'?<div className="maintenance-lock-note"><Wrench/>Борт заблокирован для назначения полётов на всё сервисное окно.</div>:selected.simulation&&<button className={`mission-replay-action ${selected.status==='planned'?'simulation':selected.status==='active'?'live':''}`} onClick={()=>onReplay(selected)}>{selected.status==='completed'?<History/>:<Play/>}{selected.status==='planned'?'Открыть симуляцию':selected.status==='active'?'Открыть текущий полёт':'Смотреть повтор полёта'}</button>}{selected.source==='planner'&&selected.simulation?.missionId&&<MissionExportActions missionId={selected.simulation.missionId} planId={selected.simulation.planId} compact/>}</>:<p>Нажмите на событие в календаре.</p>}</section>
      <section className="workload-card"><header><h2>Загрузка по неделям</h2><small>план + факт, ч</small></header>{[1,2,3,4,5].map(week=>{const value=filtered.filter(m=>Math.ceil(Number(m.date.slice(-2))/7)===week).reduce((sum,m)=>sum+m.duration,0);return <div key={week}><span>{week} неделя</span><i><b style={{width:`${Math.min(100,value/20*100)}%`}}/></i><strong>{value.toFixed(1)}</strong></div>})}</section></aside></div>
    {selectedDay&&<DayPlan date={selectedDay} missions={modeMissions} uavs={uavs} onClose={()=>setSelectedDay(null)} onMission={mission=>{setSelectedId(mission.id);setSelectedDay(null)}} onReplay={mission=>{setSelectedId(mission.id);setSelectedDay(null);onReplay(mission)}}/>} {maintenanceOpen&&<MaintenanceModal uavs={uavs} missions={missions} initialUavId={maintenanceDraftUavId||(uavId!=='all'?uavId:null)} onClose={()=>setMaintenanceOpen(false)} onCreate={onCreateMaintenance}/>} 
  </section>
}
