import { useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { Building2, CalendarClock, Check, ChevronRight, CircleDollarSign, FileCheck2, Mail, MapPin, Phone, Plus, Search, Send, UserRound, X } from 'lucide-react'
import type * as GeoJSON from 'geojson'

export type OrderStatus = 'new'|'qualification'|'proposal'|'approved'|'scheduled'|'in_progress'|'processing'|'qc'|'delivered'|'cancelled'
export type OrderResult = 'orthophoto'|'thermal_map'|'point_cloud'|'magnetic_map'|'powerline_report'|'digital_twin'|'ndvi'
export type CustomerOrder = {
  id:string; number:string; status:OrderStatus; title:string; result_type:OrderResult; desired_date:string; desired_time:string;
  location:string; area_km2:number; budget_rub?:number|null; priority:'normal'|'high'|'critical'; geometry:GeoJSON.Geometry;
  customer:{name:string;inn?:string|null;kpp?:string|null;ogrn?:string|null;legal_address?:string|null;management_name?:string|null;status?:string|null};
  contact:{name:string;phone:string;email:string}; requirements:Record<string,unknown>; notes:string; created_by:string;
}

type DadataSuggestion = { value?:string;inn?:string;kpp?:string;ogrn?:string;name_full?:string;name_short?:string;legal_address?:string;management_name?:string;status?:string }

const labels:Record<OrderStatus,string>={new:'Новая заявка',qualification:'Квалификация',proposal:'Предложение',approved:'Согласовано',scheduled:'Запланировано',in_progress:'Полёт',processing:'Обработка',qc:'Контроль качества',delivered:'Выдано',cancelled:'Отменено'}
const products:Record<OrderResult,string>={orthophoto:'Ортофотоплан',thermal_map:'Тепловая карта',point_cloud:'Облако точек LiDAR',magnetic_map:'Магнитная карта',powerline_report:'Обследование ЛЭП',digital_twin:'Цифровой двойник',ndvi:'Карта NDVI'}
const nextStatus:Partial<Record<OrderStatus,{status:OrderStatus;label:string}>>={new:{status:'qualification',label:'Взять в квалификацию'},qualification:{status:'proposal',label:'Подготовить предложение'},proposal:{status:'approved',label:'Заказчик согласовал'},scheduled:{status:'in_progress',label:'Начать выполнение'},in_progress:{status:'processing',label:'Передать в обработку'},processing:{status:'qc',label:'Передать на контроль'},qc:{status:'delivered',label:'Выдать результат'}}

function localDate(d=new Date()) { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }

function NewOrderModal({onClose,onCreated}:{onClose:()=>void;onCreated:(order:CustomerOrder)=>void}) {
  const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1)
  const [form,setForm]=useState({title:'',result_type:'orthophoto' as OrderResult,desired_date:localDate(tomorrow),desired_time:'09:00',location:'Москва',area_km2:'1.5',budget_rub:'',priority:'normal',customer_name:'',inn:'',kpp:'',ogrn:'',legal_address:'',management_name:'',contact_name:'',phone:'',email:'',notes:''})
  const [query,setQuery]=useState('');const [suggestions,setSuggestions]=useState<DadataSuggestion[]>([]);const [searching,setSearching]=useState(false);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false)
  const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}))
  const search=async()=>{if(query.trim().length<3)return;setSearching(true);setMessage('');try{const response=await fetch(`/api/integrations/dadata/suggest?query=${encodeURIComponent(query.trim())}`,{credentials:'include'});if(!response.ok)throw new Error();const data=await response.json();setSuggestions(data.suggestions||[]);if(data.status==='not_configured')setMessage('DaData не настроена — реквизиты можно заполнить вручную.')}catch{setMessage('Поиск временно недоступен — заполните реквизиты вручную.')}finally{setSearching(false)}}
  const apply=(item:DadataSuggestion)=>{setForm(current=>({...current,customer_name:item.name_short||item.value||'',inn:item.inn||'',kpp:item.kpp||'',ogrn:item.ogrn||'',legal_address:item.legal_address||'',management_name:item.management_name||''}));setSuggestions([]);setMessage('Реквизиты подтверждены по справочнику DaData.')}
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setMessage('');try{const payload={title:form.title,result_type:form.result_type,desired_date:form.desired_date,desired_time:form.desired_time,location:form.location,area_km2:Number(form.area_km2),budget_rub:form.budget_rub?Number(form.budget_rub):null,priority:form.priority,geometry:{type:'Polygon',coordinates:[[[37.457,55.787],[37.480,55.787],[37.480,55.777],[37.457,55.777],[37.457,55.787]]]},customer:{name:form.customer_name,inn:form.inn||null,kpp:form.kpp||null,ogrn:form.ogrn||null,legal_address:form.legal_address||null,management_name:form.management_name||null,status:'ACTIVE'},contact:{name:form.contact_name,phone:form.phone,email:form.email},requirements:{source:'customer_brief'},notes:form.notes};const response=await fetch('/api/orders',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const body=await response.json();throw new Error(typeof body.detail==='string'?body.detail:'Не удалось сохранить заявку')}onCreated(await response.json());onClose()}catch(error){setMessage(error instanceof Error?error.message:'Не удалось сохранить заявку')}finally{setSaving(false)}}
  return createPortal(<div className="order-modal-backdrop"><form className="order-modal" onSubmit={submit}><header><div><span>НОВАЯ ЗАЯВКА</span><h2>Заказ на аэросъёмку</h2><p>Карточка заказчика, требуемый результат и желаемое окно выполнения.</p></div><button type="button" onClick={onClose} aria-label="Закрыть форму"><X size={19}/></button></header>
    <section className="dadata-box"><label title="Поиск организаций выполняется с использованием сервиса DaData">Поиск организации</label><div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, ИНН или ОГРН"/><button type="button" disabled={searching||query.trim().length<3} onClick={search}><Search size={15}/>{searching?'Ищем…':'Найти'}</button></div>{suggestions.length>0&&<ul>{suggestions.map((item,index)=><li key={`${item.inn}-${index}`}><button type="button" onClick={()=>apply(item)}><strong>{item.name_short||item.value}</strong><small>ИНН {item.inn||'—'} · {item.legal_address||'адрес не указан'}</small></button></li>)}</ul>}{message&&<small className="form-message">{message}</small>}</section>
    <div className="order-form-grid"><h3>Заказчик</h3><label className="wide">Организация<input required value={form.customer_name} onChange={e=>update('customer_name',e.target.value)}/></label><label>ИНН<input value={form.inn} inputMode="numeric" onChange={e=>update('inn',e.target.value)}/></label><label>КПП<input value={form.kpp} inputMode="numeric" onChange={e=>update('kpp',e.target.value)}/></label><label className="wide">Юридический адрес<input value={form.legal_address} onChange={e=>update('legal_address',e.target.value)}/></label><label>Контактное лицо<input required value={form.contact_name} onChange={e=>update('contact_name',e.target.value)}/></label><label>Телефон<input required value={form.phone} onChange={e=>update('phone',e.target.value)}/></label><label>Email<input required type="email" value={form.email} onChange={e=>update('email',e.target.value)}/></label><h3>Параметры заявки</h3><label className="wide">Задача<input required value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Например, ортофотоплан территории строительства"/></label><label>Результат<select value={form.result_type} onChange={e=>update('result_type',e.target.value)}>{Object.entries(products).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Расположение<input required value={form.location} onChange={e=>update('location',e.target.value)}/></label><label>Желаемая дата<input required type="date" min={localDate()} value={form.desired_date} onChange={e=>update('desired_date',e.target.value)}/></label><label>Время<input required type="time" value={form.desired_time} onChange={e=>update('desired_time',e.target.value)}/></label><label>Площадь, км²<input required type="number" min="0.01" step="0.01" value={form.area_km2} onChange={e=>update('area_km2',e.target.value)}/></label><label>Бюджет, ₽<input type="number" min="0" step="1000" value={form.budget_rub} onChange={e=>update('budget_rub',e.target.value)}/></label><label className="wide">Комментарий<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} rows={3}/></label></div>
    <footer><span>Поиск организаций и заполнение реквизитов — сервис DaData.</span><button disabled={saving}><Plus size={16}/>{saving?'Сохраняем…':'Зарегистрировать заявку'}</button></footer></form></div>,document.body)
}

export function OrdersWorkspace({orders,loadError,onOrdersChange,onSendToPlanner}:{orders:CustomerOrder[];loadError?:string;onOrdersChange:(orders:CustomerOrder[])=>void;onSendToPlanner:(order:CustomerOrder)=>void}) {
  const [selectedId,setSelectedId]=useState(orders[0]?.id||'');const [creating,setCreating]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');const [statusFilter,setStatusFilter]=useState<'all'|'active'|'approved'>('all')
  const selected=orders.find(item=>item.id===selectedId)||orders[0]
  const stats=useMemo(()=>({active:orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length,approved:orders.filter(o=>o.status==='approved').length,pipeline:orders.reduce((sum,o)=>sum+(o.budget_rub||0),0),customers:new Set(orders.map(o=>o.customer.inn||o.customer.name)).size}),[orders])
  const visibleOrders=useMemo(()=>orders.filter(order=>(statusFilter==='all'||(statusFilter==='active'?!['delivered','cancelled'].includes(order.status):order.status==='approved'))&&`${order.number} ${order.title} ${order.customer.name} ${order.location}`.toLocaleLowerCase('ru-RU').includes(query.trim().toLocaleLowerCase('ru-RU'))),[orders,statusFilter,query])
  const advance=async()=>{if(!selected)return;const transition=nextStatus[selected.status];if(!transition)return;setBusy(true);setError('');try{const response=await fetch(`/api/orders/${selected.id}/status`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:transition.status,note:transition.label})});if(!response.ok){const body=await response.json();throw new Error(body.detail||'Переход недоступен')}const updated=await response.json();onOrdersChange(orders.map(item=>item.id===updated.id?updated:item))}catch(problem){setError(problem instanceof Error?problem.message:'Не удалось обновить заказ')}finally{setBusy(false)}}
  return <section className="orders-workspace"><div className="orders-title"><div><span>КОММЕРЧЕСКИЙ КОНТУР</span><h1>Заказы на аэросъёмку</h1><p>От потребности заказчика до выполнимого задания, контроля качества и выдачи результата.</p></div><button onClick={()=>setCreating(true)}><Plus size={17}/>Новая заявка</button></div>
    <div className="order-kpis"><button className={statusFilter==='active'?'selected':''} onClick={()=>setStatusFilter(statusFilter==='active'?'all':'active')} title="Показать заявки в работе"><FileCheck2/><span><small>В работе</small><b>{stats.active}</b></span></button><button className={statusFilter==='approved'?'selected':''} onClick={()=>setStatusFilter(statusFilter==='approved'?'all':'approved')} title="Показать заявки, ожидающие планирования"><Check/><span><small>Ждут планирования</small><b>{stats.approved}</b></span></button><button onClick={()=>setStatusFilter('all')} title="Показать все заявки"><CircleDollarSign/><span><small>Портфель</small><b>{Math.round(stats.pipeline/1000).toLocaleString('ru-RU')} тыс. ₽</b></span></button><button onClick={()=>setStatusFilter('all')} title="Показать всех заказчиков"><Building2/><span><small>Заказчики</small><b>{stats.customers}</b></span></button></div>
    <div className="orders-layout"><div className="orders-list"><header><strong>Реестр заявок</strong><span>{visibleOrders.length}</span></header><div className="orders-list-filter"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Номер, заказчик, объект" aria-label="Поиск заявок"/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as 'all'|'active'|'approved')} aria-label="Фильтр заявок"><option value="all">Все</option><option value="active">В работе</option><option value="approved">К планированию</option></select></div>{loadError?<div className="orders-empty error"><strong>Реестр временно недоступен</strong><small>{loadError}</small></div>:visibleOrders.length===0?<div className="orders-empty"><strong>{orders.length?'Ничего не найдено':'Заявок пока нет'}</strong><small>{orders.length?'Измените поиск или фильтр.':'Создайте первую заявку — она появится в коммерческом контуре.'}</small></div>:visibleOrders.map(order=><button key={order.id} className={order.id===selected?.id?'selected':''} onClick={()=>setSelectedId(order.id)}><i className={`order-status ${order.status}`}/><div><span><b>{order.number}</b><em className={order.priority}>{order.priority==='critical'?'Срочно':order.priority==='high'?'Высокий':'Обычный'}</em></span><strong>{order.title}</strong><small>{order.customer.name} · {order.location}</small></div><ChevronRight size={17}/></button>)}</div>
      {selected&&<article className="order-detail"><header><div><span>{selected.number} · {labels[selected.status]}</span><h2>{selected.title}</h2><p>{products[selected.result_type]} · {selected.area_km2.toLocaleString('ru-RU')} км²</p></div><em className={`order-stage ${selected.status}`}>{labels[selected.status]}</em></header><div className="order-customer"><Building2/><div><small>ЗАКАЗЧИК</small><strong>{selected.customer.name}</strong><span>ИНН {selected.customer.inn||'не указан'} · {selected.customer.legal_address||'адрес уточняется'}</span></div></div><div className="order-facts"><span><CalendarClock/><small>Желаемое окно</small><b>{selected.desired_date.split('-').reverse().join('.')} · {selected.desired_time}</b></span><span><MapPin/><small>Объект</small><b>{selected.location}</b></span><span><CircleDollarSign/><small>Бюджет</small><b>{selected.budget_rub?`${selected.budget_rub.toLocaleString('ru-RU')} ₽`:'уточняется'}</b></span><span><UserRound/><small>Контакт</small><b>{selected.contact.name}</b></span></div><div className="order-contact"><span><Phone size={14}/>{selected.contact.phone}</span><span><Mail size={14}/>{selected.contact.email}</span></div><section className="order-notes"><small>ИСХОДНЫЕ ТРЕБОВАНИЯ</small><p>{selected.notes||'Требования будут уточнены на этапе квалификации.'}</p></section><footer>{selected.status==='approved'?<button className="primary" onClick={()=>onSendToPlanner(selected)}><Send size={16}/>Передать в планировщик</button>:nextStatus[selected.status]?<button className="primary" disabled={busy} onClick={advance}><Check size={16}/>{busy?'Сохраняем…':nextStatus[selected.status]!.label}</button>:<span>Этап завершён — дальнейших действий не требуется.</span>}</footer></article>}
    </div>{error&&<div className="order-action-error">{error}</div>}{creating&&<NewOrderModal onClose={()=>setCreating(false)} onCreated={order=>{onOrdersChange([order,...orders]);setSelectedId(order.id)}}/>}</section>
}
